---

name: Build Production Docker Image
on: "push"

jobs:
    build-docker:
        name: "Build Production Docker Image"
        runs-on: "ubuntu-latest"
        env:
            GITHUB_REPOSITORY_FULL_NAME: ${{ github.repository }}
        steps:
            - name: "Checkout repository"
              uses: "actions/checkout@v2"
              
            - name: "Create repository names"
              run: |
                  docker_latest=docker.pkg.github.com/${{ github.repository }}/${GITHUB_REPOSITORY_FULL_NAME##*/}:latest
                  docker_tag_production=docker.pkg.github.com/${{ github.repository }}/${GITHUB_REPOSITORY_FULL_NAME##*/}:${{ github.sha }}
                  echo ${docker_latest}

            - name: "Build Docker image"
              run: docker build --tag docker.pkg.github.com/${{ github.repository }}/${GITHUB_REPOSITORY_FULL_NAME##*/}:latest .

            - name: "Login to GitHub"
              run: echo "${{ secrets.GH_TOKEN }}" | docker login docker.pkg.github.com -u "${{ github.repository_owner }}" --password-stdin
            
            - name: "Tag and publish"
              run: |
                  docker tag "${docker_latest,,}" "${docker_tag_production,,}"
                  docker push "${docker_tag_production,,}"
                  docker push "${docker_latest,,}"
