---

name: Build Production Docker Image
on: "push"

jobs:
    build-docker:
        name: "Build Production Docker Image"
        runs-on: "ubuntu-latest"
        steps:
            - name: "Checkout repository"
              uses: "actions/checkout@v2"
              
            - name: "Create repository names"
              run: |
                  github_repository_full_name=${{ github.repository }}
                  docker_latest=docker.pkg.github.com/${{ github.repository }}/${github_repository_full_name##*/}:latest
                  docker_tag_production=docker.pkg.github.com/${{ github.repository }}/${github_repository_full_name##*/}:${{ github.sha }}

            - name: "Build Docker image"
              run: docker build --tag ${docker_latest,,} .

            - name: "Login to GitHub"
              run: echo "${{ secrets.GH_TOKEN }}" | docker login docker.pkg.github.com -u "${{ github.repository_owner }}" --password-stdin
            
            - name: "Tag and publish"
              run: |
                  docker tag "${docker_latest,,}" "${docker_tag_production,,}"
                  docker push "${docker_tag_production,,}"
                  docker push "${docker_latest,,}"
